In [308]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_rows",None)

In [51]:
file = pd.read_csv("/Users/swethag/Desktop/@Upgrad_Data_Science/Python Docs/Self Study From Upgrad/Course 5/Advanced DataBase Programming using Pandas/v1.2.csv")
file.head(4)

,Unnamed: 0,Unnamed: 1,GLASSDOOR JOBS,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Competitors,Revenue,Sector,Industry,Ownership Type,Founded,Size,Headquarters,Location,Name,Rating,Description,Salary,Title,index
3,"EmblemHealth, UnitedHealth Group, Aetna",Unknown / Non-Applicable,Insurance,Insurance Carriers,Nonprofit Organization,1993,1001 to 5000 employees,"New York, NY","New York, NY",Healthfirst\n3.1,3.1,Description\n\nThe Senior Data Scientist is re...,$137K-$171K (Glassdoor est.),Sr Data Scientist,0

In [204]:
### Removing 3 rows and making 2nd row as index using header = 2

df = pd.read_csv("/Users/swethag/Desktop/@Upgrad_Data_Science/Python Docs/Self Study From Upgrad/Course 5/Advanced DataBase Programming using Pandas/v1.2.csv",header = 3)
df.head()

,Competitors,Revenue,Sector,Industry,Ownership Type,Founded,Size,Headquarters,Location,Name,Rating,Description,Salary,Title,index
0,"EmblemHealth, UnitedHealth Group, Aetna",Unknown / Non-Applicable,Insurance,Insurance Carriers,Nonprofit Organization,1993,1001 to 5000 employees,"New York, NY","New York, NY",Healthfirst\n3.1,3.1,Description\n\nThe Senior Data Scientist is re...,$137K-$171K (Glassdoor est.),Sr Data Scientist,0
1,-1,$1 to $2 billion (USD),Business Services,Research & Development,Company - Public,1968,5001 to 10000 employees,"Herndon, VA","Chantilly, VA",ManTech\n4.2,4.2,"Secure our Nation, Ignite your Future\n\nJoin ...",$137K-$171K (Glassdoor est.),Data Scientist,1
2,-1,$100 to $500 million (USD),Business Services,Consulting,Private Practice / Firm,1981,1001 to 5000 employees,"Boston, MA","Boston, MA",Analysis Group\n3.8,3.8,Overview\n\n\nAnalysis Group is one of the lar...,$137K-$171K (Glassdoor est.),Data Scientist,2
3,"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",$100 to $500 million (USD),Manufacturing,Electrical & Electronic Manufacturing,Company - Public,2000,501 to 1000 employees,"Bad Ragaz, Switzerland","Newton, MA",INFICON\n3.5,3.5,JOB DESCRIPTION:\n\nDo you have a passion for ...,$137K-$171K (Glassdoor est.),Data Scientist,3
4,"Commerce Signals, Cardlytics, Yodlee",Unknown / Non-Applicable,Business Services,Advertising & Marketing,Company - Private,1998,51 to 200 employees,"New York, NY","New York, NY",Affinity Solutions\n2.9,2.9,Data Scientist\nAffinity Solutions / Marketing...,$137K-$171K (Glassdoor est.),NaN,4

In [205]:
# dropping index column as it ti not required 
df.drop("index",axis = 1, inplace = True)

In [65]:
df.head()

,Competitors,Revenue,Sector,Industry,Ownership Type,Founded,Size,Headquarters,Location,Name,Rating,Description,Salary,Title
0,"EmblemHealth, UnitedHealth Group, Aetna",Unknown / Non-Applicable,Insurance,Insurance Carriers,Nonprofit Organization,1993,1001 to 5000 employees,"New York, NY","New York, NY",Healthfirst\n3.1,3.1,Description\n\nThe Senior Data Scientist is re...,$137K-$171K (Glassdoor est.),Sr Data Scientist
1,-1,$1 to $2 billion (USD),Business Services,Research & Development,Company - Public,1968,5001 to 10000 employees,"Herndon, VA","Chantilly, VA",ManTech\n4.2,4.2,"Secure our Nation, Ignite your Future\n\nJoin ...",$137K-$171K (Glassdoor est.),Data Scientist
2,-1,$100 to $500 million (USD),Business Services,Consulting,Private Practice / Firm,1981,1001 to 5000 employees,"Boston, MA","Boston, MA",Analysis Group\n3.8,3.8,Overview\n\n\nAnalysis Group is one of the lar...,$137K-$171K (Glassdoor est.),Data Scientist
3,"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",$100 to $500 million (USD),Manufacturing,Electrical & Electronic Manufacturing,Company - Public,2000,501 to 1000 employees,"Bad Ragaz, Switzerland","Newton, MA",INFICON\n3.5,3.5,JOB DESCRIPTION:\n\nDo you have a passion for ...,$137K-$171K (Glassdoor est.),Data Scientist
4,"Commerce Signals, Cardlytics, Yodlee",Unknown / Non-Applicable,Business Services,Advertising & Marketing,Company - Private,1998,51 to 200 employees,"New York, NY","New York, NY",Affinity Solutions\n2.9,2.9,Data Scientist\nAffinity Solutions / Marketing...,$137K-$171K (Glassdoor est.),NaN

In [64]:
### Checking Value_counts() for all columns

for i in df.columns:
    print(i,":-",df[i].value_counts(),"\n","-"*50)

Competitors :- Competitors
-1                                                                                              512
Roche, GlaxoSmithKline, Novartis                                                                 10
Los Alamos National Laboratory, Battelle, SRI International                                       6
Leidos, CACI International, Booz Allen Hamilton                                                   6
IMAGE Skincare, Aveda, Kiehl's                                                                    4
                                                                                               ...
Los Alamos National Laboratory, NASA Jet Propulsion Laboratory, Sandia National Laboratories      1
Fluor, Bechtel, AECOM                                                                             1
Intertek, SGS, Bureau Veritas                                                                     1
Lockheed Martin, Caterpillar, John Deere                                                          1
Genomic Health, Myriad Genetics, The Broad Institute                                              1
Name: count, Length: 108, dtype: int64
 --------------------------------------------------
Revenue :- Revenue
Unknown / Non-Applicable            219
$100 to $500 million (USD)           98
$10+ billion (USD)                   64
$2 to $5 billion (USD)               46
$10 to $25 million (USD)             42
$1 to $2 billion (USD)               37
$25 to $50 million (USD)             37
$50 to $100 million (USD)            32
$1 to $5 million (USD)               32
-1                                   27
$500 million to $1 billion (USD)     19
$5 to $10 million (USD)              14
Less than $1 million (USD)           14
$5 to $10 billion (USD)               8
Name: count, dtype: int64
 --------------------------------------------------
Sector :- Sector
Information Technology                194
Business Services                     121
-1                                     71
Biotech & Pharmaceuticals              69
Aerospace & Defense                    47
Finance                                34
Insurance                              33
Manufacturing                          24
Health Care                            22
Government                             17
Oil, Gas, Energy & Utilities           10
Retail                                  8
Transportation & Logistics              7
Telecommunications                      7
Media                                   5
Real Estate                             3
Travel & Tourism                        3
Agriculture & Forestry                  3
Education                               3
Accounting & Legal                      3
Construction, Repair & Maintenance      2
Consumer Services                       2
Non-Profit                              1
Name: count, dtype: int64
 --------------------------------------------------
Industry :- Industry
-1                                          71
Biotech & Pharmaceuticals                   69
IT Services                                 62
Computer Hardware & Software                58
Aerospace & Defense                         47
Enterprise Software & Network Solutions     45
Consulting                                  38
Staffing & Outsourcing                      37
Internet                                    29
Insurance Carriers                          28
Advertising & Marketing                     23
Health Care Services & Hospitals            22
Research & Development                      17
Federal Agencies                            16
Investment Banking & Asset Management       14
Banks & Credit Unions                        8
Lending                                      8
Consumer Products Manufacturing              6
Energy                                       5
Insurance Agencies & Brokerages              5
Telecommunications Services                  5
Food & Beverage Manufacturing                4
Utilities                                    3
Electrical & Electronic Manufacturing        3
Colleges & Universities                      3
Other Retail Stores                          3
Architectural & Engineering Services         3
Chemical Manufacturing                       3
Real Estate                                  3
Miscellaneous Manufacturing                  3
Consumer Electronics & Appliances Stores     3
Video Games                                  3
Express Delivery Services                    3
Industrial Manufacturing                     3
Wholesale                                    3
Accounting                                   3
Transportation Equipment Manufacturing       2
Oil & Gas Services                           2
Construction                                 2
Financial Transaction Processing             2
Timber Operations                            2
Venture Capital & Private Equity             2
Travel Agencies                              2
Health, Beauty, & Fitness                    2
Publishing                                   1
Department, Clothing, & Shoe Stores          1
Logistics & Supply Chain                     1
Social Assistance                            1
Farm Support Services                        1
Transportation Management                    1
State & Regional Agencies                    1
Hotels, Motels, & Resorts                    1
Food & Beverage Stores                       1
News Outlet                                  1
Telecommunications Manufacturing             1
Cable, Internet & Telephone Providers        1
Shipping                                     1
Rail                                         1
Name: count, dtype: int64
 --------------------------------------------------
Ownership Type :- Ownership Type
Company - Private                 409
Company - Public                  156
Nonprofit Organization             37
Subsidiary or Business Segment     29
-1                                 27
Government                         10
Other Organization                  5
Private Practice / Firm             4
Unknown                             4
College / University                3
Self-employed                       2
Contract                            2
Hospital                            1
Name: count, dtype: int64
 --------------------------------------------------
Founded :- Founded
-1       119
 2012     36
 2011     26
 2010     24
 2015     23
        ...
 1849      1
 1953      1
 1957      1
 1961      1
 1962      1
Name: count, Length: 103, dtype: int64
 --------------------------------------------------
Size :- Size
51 to 200 employees        138
1001 to 5000 employees     109
201 to 500 employees        89
1 to 50 employees           87
10000+ employees            81
501 to 1000 employees       79
5001 to 10000 employees     62
-1                          27
Unknown                     17
Name: count, dtype: int64
 --------------------------------------------------
Headquarters :- Headquarters
New York, NY         34
San Francisco, CA    33
-1                   31
Chicago, IL          24
Boston, MA           19
                     ..
Holyoke, MA           1
Dallas, TX            1
Dulles, VA            1
Livermore, CA         1
Fort Lee, NJ          1
Name: count, Length: 229, dtype: int64
 --------------------------------------------------
Location :- Location
San Francisco, CA    71
New York, NY         51
Washington, DC       26
Boston, MA           24
Chicago, IL          23
                     ..
Oshkosh, WI           1
Culver City, CA       1
Lake Oswego, OR       1
Holyoke, MA           1
Irwindale, CA         1
Name: count, Length: 207, dtype: int64
 --------------------------------------------------
Name :- Name
Hatch Data Inc               12
Tempus Labs\n3.3             12
Maxar Technologies\n3.5      12
AstraZeneca\n4.0             10
Klaviyo\n4.8                  8
                             ..
Insider Inc\n3.3              1
Gallup\n4.1                   1
Parker Hannifin\n3.3          1
Better Hire\n4.0              1
ChaTeck Incorporated\n5.0     1
Name: count, Length: 432, dtype: int64
 --------------------------------------------------
Rating :- Rating
3.5      61
-1       50
3.3      42
3.8      40
4        40
3.9      40
3.7      40
5        36
4.5      34
3.6      31
3.4      31
4.2      29
4.1      26
3.2      22
4.4      22
4.7      21
4.8      20
4.3      13
2.9      13
4.6      12
3.1      12
4.9      11
2.7      10
3         7
2.6       4
2.8       3
2.5       3
2*+.9     1
2.1       1
2.3       1
5.2       1
2.4       1
3.8*/     1
/3.7      1
2.2       1
5.6       1
4.4*      1
2         1
Name: count, dtype: int64
 --------------------------------------------------
Description :- Description
Job Overview: The Data Scientist is a key member of our cross-functional Product team responsible for discovering new and innovative solutions to the challenges within the built environment. Now, more than ever, building owners and operators rely on Hatch Data to get a birds-eye view of asset performance to help them achieve ambitious goals around sustainable financial, environmental, and social impact. We are actively seeking an exceptional Data Scientist to help us take one of the worlds most extensive data sets for commercial building operations and transform it into amazing products for our customers.\n\nResponsibilities and Duties:\nPartner with Product Management, to Investigate high-level questions to discover new relationships between operations and outcomes\nMaintain and improve upon the accuracy and utility of existing machine-learning algorithms\nOwn the long-term Data Science Roadmap, including prototype solutions in "green field" problem spaces\nSupport ad-hoc data analysis in support of customer success and marketing efforts\nCollaborate closely with domain experts in energy and mechanical engineering, as well as with the software engineering team\nCoach and mentor others to amplify your impact and continuously demonstrate the value of data science\nExperience:\nBachelors degree in Data Science, Computer Science, Math, or related technical field.\nMinimum 3+ years experience applying data science techniques to drive product development and decision-making.\nDemonstrated track record of solving problems in industry with machine learning\nExpertise in statistical methods and experimental design and analysis\nFluent in at least one modern language for data processing (R, Python, and Scala experience ideal).\nComfortable with AWS and distributed data processing systems (e.g., Spark)\nFamiliarity with energy-efficiency, commercial building domain, regression and baseline techniques, weather normalization, etc. a plus\nExperience using APIs to manipulation and move data in and out of systems.\nMust possess outstanding written and verbal communication skills in English.\nAbility to prioritize development and operational tasks in a dynamic and challenging environment.\nAbout You:\nCare about leaving the world better than you found it.\nMission-driven and leads by example with equal parts brain and heart.\nOperationally-minded, empathetic, self-starter, driven, and gets things done.\nNatural communicator that instills confidence and trust with internal and external stakeholders.\nExcited to join a small company, with big company benefits, and upside potential.\nIdeally based in the San Francisco Bay Area.\nAbout Us:\n\nClimate change is real. Addressing this is the biggest issue of our time. While moving the world from dirty energy sources to clean ones matters, there is also an enormous opportunity to use existing resources more efficiently. Buildings consume up to 40% of the energy in North America alone. This is a big opportunity to create change. We bring our values to work and every day push to solve these problems at scale.\n\nOur team applies their knowledge of energy systems, mechanical engineering, IoT, machine learning and the built environment, to design cutting edge software that reduces the negative environmental impact of our indoor spaces while improving the bottom line for owners and operators. Our software platform has been proven across more than 400M square feet of commercial real estate with marquee customers, and were doubling down our efforts in the coming months as we prepare to accelerate growth and impact.\n\nThis is a unique opportunity to join a company that does well by doing good and is positioned for significant expansion. Youll enjoy comprehensive benefits, competitive salary, and meaningful equity. We offer a flexible work environment and the opportunity to work alongside an incredibly talented, fun, and highly motivated team.\n\nHow to Apply:\n\nDoes this sound like you? If so, please submit your resume and cover letter and provide any context you think would be helpful as we learn about you. Well be interested in understanding why youre excited about joining us, why this role seems like a perfect fit for your talents, and what success looks like for you, personally, over the next few years.                                                                                                                                                                                                                                                                                                                                                                                                                                                          12
We love programming and the excitement that comes with building something people use. We are the kind of people that love talking to users and can find the balance between solving a problem quickly and thinking about how your code will work in the future. We love to move fast, keep learning and get stuff done.\n\nOur data science team is still in its early days and you'll have a big impact on our direction and how we operate. You'll be central to researching, developing and shipping products that help our customers learn and grow from their data. For this role, we're looking for people who have developed split brains--software engineers who have become great at writing machine learning code or data scientists who have become great software developers.\n\nTechnologies we use (not comprehensive!):\nPython\n\nNumpy, Scipy, Pandas\n\nAurora, Cassandra, Kafka\n\nHTML, JavaScript, React\n\nSageMaker\n\nHow you will make a difference:\n\n\nAnalyze large data sets (we're collecting billions of individual actions every month).\nBuild products that enable our customers to grow faster and communicate more effectively with their customers.\nDevelop machine learning models and pipelines for research and production.\n\nWho You Are:\n\n\nHave experience implementing machine learning models, data pipelines and testing frameworks for research and production use.\nHave demonstrated a measurable impact based on the models you've created. It's not always easy getting a model correct, we love talking about places we got stuck and work as a team to think through ideas that could unblock us.\nHave experience processing cloud-scale data using parallel, elastic, streaming and similar techniques.\nEnjoy tuning and validating machine learning models and take a rigorous approach.\nUnderstand how to profile code and optimize performance.\nAspire to correctness (e.g. in your code, in drawing conclusions from data)\nHave a bachelor's or advanced degree in computer science, applied math, statistics or other relevant quantitative discipline, or equivalent industry experience.\n\nGet to know Klaviyo\n\nKlaviyo is the world's leading owned marketing platform known for accelerating revenue for online businesses using the channels they own like email, web, and mobile. Enabling companies to leverage these owned marketing channels, Klaviyo makes it easy to store, access, analyze and use transactional and behavioral data to power highly-targeted customer and prospect communications. And unlike other marketing platforms, Klaviyo doesn't force companies to compromise between advanced functionality or ease of use - so companies of all sizes are able to maximize their sales quickly. That's why over 28,000+ innovative companies like Unilever, Custom Ink and Eventbrite sell more with Klaviyo.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  5

In [45]:
df.columns

Index(['Competitors', 'Revenue', 'Sector', 'Industry', 'Ownership Type',
       'Founded', 'Size', 'Headquarters', 'Location', 'Name', 'Rating',
       'Description', 'Salary', 'Title'],
      dtype='object')

In [206]:
l1 = "C_" + df.columns[0:11] ### Company
l1

Index(['C_Competitors', 'C_Revenue', 'C_Sector', 'C_Industry',
       'C_Ownership Type', 'C_Founded', 'C_Size', 'C_Headquarters',
       'C_Location', 'C_Name', 'C_Rating'],
      dtype='object')

In [207]:
l2 = "J_" + df.columns[11:14] ### Job 
l2

Index(['J_Description', 'J_Salary', 'J_Title'], dtype='object')

In [208]:
new_list= l1.append(l2)
new_list

Index(['C_Competitors', 'C_Revenue', 'C_Sector', 'C_Industry',
       'C_Ownership Type', 'C_Founded', 'C_Size', 'C_Headquarters',
       'C_Location', 'C_Name', 'C_Rating', 'J_Description', 'J_Salary',
       'J_Title'],
      dtype='object')

In [209]:
df.columns = new_list

In [210]:
df.columns

Index(['C_Competitors', 'C_Revenue', 'C_Sector', 'C_Industry',
       'C_Ownership Type', 'C_Founded', 'C_Size', 'C_Headquarters',
       'C_Location', 'C_Name', 'C_Rating', 'J_Description', 'J_Salary',
       'J_Title'],
      dtype='object')

In [71]:
df2 = df.copy()
df2.head(2)

,C_Competitors,C_Revenue,C_Sector,C_Industry,C_Ownership Type,C_Founded,C_Size,C_Headquarters,C_Location,C_Name,C_Rating,J_Description,J_Salary,J_Title
0,"EmblemHealth, UnitedHealth Group, Aetna",Unknown / Non-Applicable,Insurance,Insurance Carriers,Nonprofit Organization,1993,1001 to 5000 employees,"New York, NY","New York, NY",Healthfirst\n3.1,3.1,Description\n\nThe Senior Data Scientist is re...,$137K-$171K (Glassdoor est.),Sr Data Scientist
1,-1,$1 to $2 billion (USD),Business Services,Research & Development,Company - Public,1968,5001 to 10000 employees,"Herndon, VA","Chantilly, VA",ManTech\n4.2,4.2,"Secure our Nation, Ignite your Future\n\nJoin ...",$137K-$171K (Glassdoor est.),Data Scientist

In [72]:
df2 = df2.add_prefix("GlassDoor_")
df2.head(2)

,GlassDoor_C_Competitors,GlassDoor_C_Revenue,GlassDoor_C_Sector,GlassDoor_C_Industry,GlassDoor_C_Ownership Type,GlassDoor_C_Founded,GlassDoor_C_Size,GlassDoor_C_Headquarters,GlassDoor_C_Location,GlassDoor_C_Name,GlassDoor_C_Rating,GlassDoor_J_Description,GlassDoor_J_Salary,GlassDoor_J_Title
0,"EmblemHealth, UnitedHealth Group, Aetna",Unknown / Non-Applicable,Insurance,Insurance Carriers,Nonprofit Organization,1993,1001 to 5000 employees,"New York, NY","New York, NY",Healthfirst\n3.1,3.1,Description\n\nThe Senior Data Scientist is re...,$137K-$171K (Glassdoor est.),Sr Data Scientist
1,-1,$1 to $2 billion (USD),Business Services,Research & Development,Company - Public,1968,5001 to 10000 employees,"Herndon, VA","Chantilly, VA",ManTech\n4.2,4.2,"Secure our Nation, Ignite your Future\n\nJoin ...",$137K-$171K (Glassdoor est.),Data Scientist

### Re-Ordering the columns

In [179]:
###Solution 1

list(df.columns[11:]) + list(df.columns[:11])

['J_Description',
 'J_Salary',
 'J_Title',
 'C_Competitors',
 'C_Revenue',
 'C_Sector',
 'C_Industry',
 'C_Ownership Type',
 'C_Founded',
 'C_Size',
 'C_Headquarters',
 'C_Location',
 'C_Name',
 'C_Rating']

In [180]:
df = df[list(df.columns[11:]) + list(df.columns[:11])]
df.head(2)

,J_Description,J_Salary,J_Title,C_Competitors,C_Revenue,C_Sector,C_Industry,C_Ownership Type,C_Founded,C_Size,C_Headquarters,C_Location,C_Name,C_Rating
0,Description\n\nThe Senior Data Scientist is re...,$137K-$171K (Glassdoor est.),Sr Data Scientist,"EmblemHealth, UnitedHealth Group, Aetna",Unknown / Non-Applicable,Insurance,Insurance Carriers,Nonprofit Organization,1993,1001 to 5000 employees,"New York, NY","New York, NY",Healthfirst\n3.1,3.1
1,"Secure our Nation, Ignite your Future\n\nJoin ...",$137K-$171K (Glassdoor est.),Data Scientist,-1,$1 to $2 billion (USD),Business Services,Research & Development,Company - Public,1968,5001 to 10000 employees,"Herndon, VA","Chantilly, VA",ManTech\n4.2,4.2

In [211]:
### Solution 2

df = df.loc[:, ::-1]
df.head(2)

,J_Title,J_Salary,J_Description,C_Rating,C_Name,C_Location,C_Headquarters,C_Size,C_Founded,C_Ownership Type,C_Industry,C_Sector,C_Revenue,C_Competitors
0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1

### DataType Check

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689 entries, 0 to 688
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   J_Description     689 non-null    object
 1   J_Salary          689 non-null    object
 2   J_Title           684 non-null    object
 3   C_Competitors     689 non-null    object
 4   C_Revenue         689 non-null    object
 5   C_Sector          689 non-null    object
 6   C_Industry        689 non-null    object
 7   C_Ownership Type  689 non-null    object
 8   C_Founded         689 non-null    int64
 9   C_Size            689 non-null    object
 10  C_Headquarters    689 non-null    object
 11  C_Location        689 non-null    object
 12  C_Name            689 non-null    object
 13  C_Rating          684 non-null    object
dtypes: int64(1), object(13)
memory usage: 75.5+ KB

In [45]:
df.C_Rating.value_counts()

C_Rating
3.5      61
-1       50
3.3      42
3.8      40
4        40
3.9      40
3.7      40
5        36
4.5      34
3.6      31
3.4      31
4.2      29
4.1      26
3.2      22
4.4      22
4.7      21
4.8      20
4.3      13
2.9      13
4.6      12
3.1      12
4.9      11
2.7      10
3         7
2.6       4
2.8       3
2.5       3
2*+.9     1
2.1       1
2.3       1
5.2       1
2.4       1
3.8*/     1
/3.7      1
2.2       1
5.6       1
4.4*      1
2         1
Name: count, dtype: int64

In [76]:
### Checking missing values
df.isnull().mean()*100

C_Rating            0.725689
C_Name              0.000000
C_Location          0.000000
C_Headquarters      0.000000
C_Size              0.000000
C_Founded           0.000000
C_Ownership Type    0.000000
C_Industry          0.000000
C_Sector            0.000000
C_Revenue           0.000000
C_Competitors       0.000000
J_Title             0.725689
J_Salary            0.000000
J_Description       0.000000
dtype: float64

In [77]:
df[df["C_Rating"].isna()]

,C_Rating,C_Name,C_Location,C_Headquarters,C_Size,C_Founded,C_Ownership Type,C_Industry,C_Sector,C_Revenue,C_Competitors,J_Title,J_Salary,J_Description
49,NaN,Quick Base\n4.3,"Cambridge, MA","Cambridge, MA",201 to 500 employees,1999,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,Data Scientist,$75K-$131K (Glassdoor est.),Company Description:\nWhats it like to work at...
67,NaN,Grid Dynamics\n4.0,"Santa Clara, CA","San Ramon, CA",1001 to 5000 employees,2006,Company - Private,Enterprise Software & Network Solutions,Information Technology,$50 to $100 million (USD),"Luxoft, EPAM, Capgemini Invent",Data Scientist,$79K-$131K (Glassdoor est.),"As a member of the Data Science team, this rol..."
157,NaN,Guzman & Griffin Technologies (GGTI)\n4.4,"Washington, DC","Mays Landing, NJ",1 to 50 employees,1997,Company - Private,Federal Agencies,Government,Unknown / Non-Applicable,-1,Experienced Data Scientist,$101K-$165K (Glassdoor est.),*******Please Apply using this link: https://a...
350,NaN,Praxis Engineering\n4.7,"Chantilly, VA","Annapolis Junction, MD",201 to 500 employees,2002,Subsidiary or Business Segment,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),"Raytheon Technologies, Northrop Grumman, Booz ...",Data Scientist,$122K-$146K (Glassdoor est.),What will you be doing?\n\nThe Contractor shal...
686,NaN,Grid Dynamics\n4.0,"Santa Clara, CA","San Ramon, CA",1001 to 5000 employees,2006,Company - Private,Enterprise Software & Network Solutions,Information Technology,$50 to $100 million (USD),"Luxoft, EPAM, Capgemini Invent",Data Scientist,$79K-$131K (Glassdoor est.),"As a member of the Data Science team, this rol..."

In [97]:
### Replacing the "na" values

df[df.C_Rating.isna()].shape

(5, 14)

In [212]:
### Storing the index value in a var

index_C_Rating = df[df.C_Rating.isna()].index
index_C_Rating

Index([49, 67, 157, 350, 686], dtype='int64')

In [233]:
len(index_C_Rating)

5

In [234]:
ls = []
for i in range(0, len(index_C_Rating)):
    ls.append(df.iloc[index_C_Rating[i]]['C_Name'].split('\n')[1])

In [235]:
ls

['4.3', '4.0', '4.4', '4.7', '4.0']

In [236]:
df.iloc[index_C_Rating,3] = ls

In [242]:
### NULL values is replaced 
df.iloc[index_C_Rating]

,J_Title,J_Salary,J_Description,C_Rating,C_Name,C_Location,C_Headquarters,C_Size,C_Founded,C_Ownership Type,C_Industry,C_Sector,C_Revenue,C_Competitors
49,Data Scientist,$75K-$131K (Glassdoor est.),Company Description:\nWhats it like to work at...,4.3,Quick Base\n4.3,"Cambridge, MA","Cambridge, MA",201 to 500 employees,1999,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
67,Data Scientist,$79K-$131K (Glassdoor est.),"As a member of the Data Science team, this rol...",4.0,Grid Dynamics\n4.0,"Santa Clara, CA","San Ramon, CA",1001 to 5000 employees,2006,Company - Private,Enterprise Software & Network Solutions,Information Technology,$50 to $100 million (USD),"Luxoft, EPAM, Capgemini Invent"
157,Experienced Data Scientist,$101K-$165K (Glassdoor est.),*******Please Apply using this link: https://a...,4.4,Guzman & Griffin Technologies (GGTI)\n4.4,"Washington, DC","Mays Landing, NJ",1 to 50 employees,1997,Company - Private,Federal Agencies,Government,Unknown / Non-Applicable,-1
350,Data Scientist,$122K-$146K (Glassdoor est.),What will you be doing?\n\nThe Contractor shal...,4.7,Praxis Engineering\n4.7,"Chantilly, VA","Annapolis Junction, MD",201 to 500 employees,2002,Subsidiary or Business Segment,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),"Raytheon Technologies, Northrop Grumman, Booz ..."
686,Data Scientist,$79K-$131K (Glassdoor est.),"As a member of the Data Science team, this rol...",4.0,Grid Dynamics\n4.0,"Santa Clara, CA","San Ramon, CA",1001 to 5000 employees,2006,Company - Private,Enterprise Software & Network Solutions,Information Technology,$50 to $100 million (USD),"Luxoft, EPAM, Capgemini Invent"

In [213]:
### Getting the wrong values and storing it in list

for i in (df[~df.C_Rating.isna()] ["C_Rating"]):
    if len(i) > 3:
        print(i)

4.4*
/3.7
3.8*/
2*+.9

In [215]:
l = []

for i in df["C_Rating"]:
    try:
        pd.to_numeric(i)
    except ValueError:
        l.append(i)
print("Erronous list are",l)

Erronous list are ['4.4*', '/3.7', '3.8*/', '2*+.9']

In [90]:
df.C_Rating

0      3.1
1      4.2
2      3.8
3      3.5
4      2.9
      ...
684    3.7
685    3.7
686    NaN
687    3.3
688    2.5
Name: C_Rating, Length: 689, dtype: object

In [222]:
df.iloc[index_C_Rating]

,J_Title,J_Salary,J_Description,C_Rating,C_Name,C_Location,C_Headquarters,C_Size,C_Founded,C_Ownership Type,C_Industry,C_Sector,C_Revenue,C_Competitors
49,Data Scientist,$75K-$131K (Glassdoor est.),Company Description:\nWhats it like to work at...,4.3,Quick Base\n4.3,"Cambridge, MA","Cambridge, MA",201 to 500 employees,1999,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
67,Data Scientist,$79K-$131K (Glassdoor est.),"As a member of the Data Science team, this rol...",4.0,Grid Dynamics\n4.0,"Santa Clara, CA","San Ramon, CA",1001 to 5000 employees,2006,Company - Private,Enterprise Software & Network Solutions,Information Technology,$50 to $100 million (USD),"Luxoft, EPAM, Capgemini Invent"
157,Experienced Data Scientist,$101K-$165K (Glassdoor est.),*******Please Apply using this link: https://a...,4.4,Guzman & Griffin Technologies (GGTI)\n4.4,"Washington, DC","Mays Landing, NJ",1 to 50 employees,1997,Company - Private,Federal Agencies,Government,Unknown / Non-Applicable,-1
350,Data Scientist,$122K-$146K (Glassdoor est.),What will you be doing?\n\nThe Contractor shal...,4.7,Praxis Engineering\n4.7,"Chantilly, VA","Annapolis Junction, MD",201 to 500 employees,2002,Subsidiary or Business Segment,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),"Raytheon Technologies, Northrop Grumman, Booz ..."
686,Data Scientist,$79K-$131K (Glassdoor est.),"As a member of the Data Science team, this rol...",4.0,Grid Dynamics\n4.0,"Santa Clara, CA","San Ramon, CA",1001 to 5000 employees,2006,Company - Private,Enterprise Software & Network Solutions,Information Technology,$50 to $100 million (USD),"Luxoft, EPAM, Capgemini Invent"

In [225]:
df.C_Rating.isna().sum()

0

In [226]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689 entries, 0 to 688
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   J_Title           684 non-null    object
 1   J_Salary          689 non-null    object
 2   J_Description     689 non-null    object
 3   C_Rating          689 non-null    object
 4   C_Name            689 non-null    object
 5   C_Location        689 non-null    object
 6   C_Headquarters    689 non-null    object
 7   C_Size            689 non-null    object
 8   C_Founded         689 non-null    int64
 9   C_Ownership Type  689 non-null    object
 10  C_Industry        689 non-null    object
 11  C_Sector          689 non-null    object
 12  C_Revenue         689 non-null    object
 13  C_Competitors     689 non-null    object
dtypes: int64(1), object(13)
memory usage: 75.5+ KB

In [251]:
### Chaning the datatype of "C_Rating" column
def cleaner(str):
    cleaner_str = "".join(filter(lambda x: (x in "0123456789."),str))
    return float(cleaner_str)

In [252]:
df.C_Rating = df["C_Rating"].apply(cleaner)

In [253]:
df['C_Rating'].dtype

dtype('float64')

__Cleaning the Name column__

In [295]:
df[['C_Name', 'Delete']] = df['C_Name'].str.split('\n', expand=True)

df.drop("Delete", axis = 1, inplace = True)

In [296]:
df.head(2)

,J_Title,J_Salary,J_Description,C_Rating,C_Name,C_Location,C_Headquarters,C_Size,C_Founded,C_Ownership Type,C_Industry,C_Sector,C_Revenue,C_Competitors
0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1

__Cleaning the Title Column__

In [309]:
df.J_Title.value_counts()

J_Title
Data Scientist                                                                                      337
Data Engineer                                                                                        27
Senior Data Scientist                                                                                20
Machine Learning Engineer                                                                            17
Data Analyst                                                                                         13
Senior Data Analyst                                                                                   6
Senior Data Engineer                                                                                  5
Data Science Software Engineer                                                                        4
Data Scientist - TS/SCI FSP or CI Required                                                            4
ENGINEER - COMPUTER SCIENTIST - RESEARCH COMPUTER SCIENTIST - SIGNAL PROCESSING - SAN ANTONIO OR      4
Data Scientist - TS/SCI Required                                                                      3
Data Modeler (Analytical Systems)                                                                     3
Data Analytics Engineer                                                                               3
Senior Machine Learning Scientist - Bay Area, CA                                                      3
Principal Data Scientist                                                                              3
Product Data Scientist - Ads Data Science                                                             3
Data Scientist - Intermediate                                                                         3
Data & Machine Learning Scientist                                                                     3
Sr. ML/Data Scientist - AI/NLP/Chatbot                                                                3
Decision Scientist                                                                                    3
AI Ops Data Scientist                                                                                 3
Senior Business Intelligence Analyst                                                                  3
Senior Data Scientist – Image Analytics, Novartis AI Innovation Lab                                   3
Analytics - Business Assurance Data Analyst                                                           3
Lead Data Scientist                                                                                   3
Data Scientist - Machine Learning                                                                     3
In-Line Inspection Data Analyst                                                                       2
Principal Scientist/Associate Director, Quality Control and Analytical Technologies                   2
Health Plan Data Analyst, Sr                                                                          2
Principal Machine Learning Scientist                                                                  2
Principal Data Scientist - Machine Learning                                                           2
Computational Behavioral Scientist                                                                    2
Sr. Data Scientist II                                                                                 2
Research Scientist - Patient-Centered Research (Remote)                                               2
Sr Data Scientist                                                                                     2
Intelligence Data Analyst, Senior                                                                     2
Machine Learning Engineer/Scientist                                                                   2
Scientist / Group Lead, Cancer Biology                                                                2
Data Scientist(s)/Machine Learning Engineer                                                           2
Senior Machine Learning Engineer                                                                      2
Senior Scientist - Toxicologist - Product Integrity (Stewardship)                                     2
Cloud Data Engineer (Azure)                                                                           2
Applied Computer Scientist                                                                            2
Weapons and Sensors Engineer/Scientist                                                                2
Data Scientist (TS/SCI w/ Poly)                                                                       2
Computer Vision / Deep Learning Scientist                                                             2
IT Partner Digital Health Technology and Data Science                                                 2
Senior Data Analyst - Finance & Platform Analytics                                                    2
Data Engineer (Analytics, SQL, Python, AWS)                                                           2
Sr. Data Scientist                                                                                    2
Scientist - Machine Learning                                                                          2
Data Engineer - Kafka                                                                                 2
VP, Data Science                                                                                      2
Data Analyst - Unilever Prestige                                                                      2
Analytics Manager - Data Mart                                                                         2
Senior Data Scientist - R&D Oncology                                                                  2
Data Scientist / Applied Mathematician                                                                2
Data Scientist/Machine Learning                                                                       2
Real World Science, Data Scientist                                                                    2
Data Scientist 3 (718)                                                                                2
Patient Safety- Associate Data Scientist                                                              2
(Sr.) Data Scientist -                                                                                2
Data Scientist, Kinship - NYC/Portland                                                                2
Experienced Data Scientist                                                                            2
Data Scientist - Contract                                                                             2
Staff Data Scientist - Analytics                                                                      2
Data Scientist / Machine Learning Expert                                                              2
Data Scientist, Applied Machine Learning - Bay Area                                                   2
Global Data Analyst                                                                                   2
E-Commerce Data Analyst                                                                               2
Jr. Data Engineer                                                                                     2
Data Scientist - Image and Video Analytics                                                            2
Data Scientist-Human Resources                                                                        2
Senior Analyst/Data Scientist                                                                         2
Business Intelligence Analyst                                                                         2
Associate Data Scientist                                                                              2
Data Scientist - Risk                                                                                 2
Senior Research Statistician- Data Scientist                                                          2
Senior Clinical Data Scientist Programmer                                                             1
Data Analyst I                                                                                        1
Data Science All Star Program - Data Engineer Track                                                   1
Lead Certified Clinical Laboratory Scientist - Saturday - Tuesday, 8:00pm - 6:30am shift              1
Applied AI Scientist / Engineer                                                                       1
Sr. Data Analyst                                                                                      1
Business Intelligence Analyst I- Data Insights                                                        1
Data Analyst II                                                                                       1
Market Research Data Scientist                                                                        1
Human Factors Scientist                                                                               1
Software Engineer (Data Scientist, C,C++,Linux,Unix) - SISW - MG                                      1
Medical Lab Scientist                                                                                 1
Data Solutions Engineer - Data Modeler                                                                1
Data Analyst/Engineer                                                                                 1
Data Modeler                                                                                          1
Principal Data & Analytics Platform Engineer                                                          1
Data Scientist/Data Analytics Practitioner                                                            1
Hydrogen/Tritium Materials Scientist (Experienced)                                                    1
Developer III - Data Science                                                                          1
Sr. Research Associate/ Scientist, NGS prep & Molecular Genomics                                      1
Lead Data Scientist – Network Analysis and Control                                                    1
Enterprise Data Analyst (Enterprise Portfolio Management Office)                                      1
Vice President, Biometrics and Clinical Data Management                                               1
Scientist/Research Associate-Metabolic Engineering                                                    1
Information Systems Engineering Specialist (Engineering Scientist)                                    1
Machine Learning Engineer, Sr.                                                                        1
Aviation AI/ML Data Scientist                                                                         1
Data Architect                                                                                        1
Big Data Engineer                                                                                     1
Data Science Manager                                                                                  1
Data Scientist Technical Specialist                                                                   1
Clinical Data Analyst                                                                                 1
Software Engineer - Machine Learning & Data Science (Applied Intelligence Services Team)              1
COMPUTER SCIENTIST - ENGINEER - RESEARCH COMPUTER SCIENTIST - TRANSPORTATION TECHNOLOGY               1
Data Science Analyst                                                                                  1
Machine Learning Scientist / Engineer                                                                 1
COMPUTER SCIENTIST - ENGINEER - RESEARCH COMPUTER SCIENTIST - SIGNAL PROCESSING                       1
Manager, Field Application Scientist, Southeast                                                       1
Senior Principal Data Scientist (Python/R)                                                            1
Data Scientist- Industrial Discrete Sector Industry                                                   1
22.3                                                                                                  1
Scientist - Molecular Biology                                                                         1
Data Engineer, Digital & Comp Pathology                                                               1
Development Scientist, Voltaren                                                                       1
Chief Scientist                                                                                       1
Staff Data Scientist                                                                                  1
Jr. Business Data Analyst (position added 6/12/2020)                                                  1
Sr Data Engineer (Sr BI Developer)                                                                    1
Data Scientist - Statistics, Early Career                                                             1
Senior Data & Machine Learning Scientist                                                              1
Senior Data Scientist - Algorithms                                                                    1
Machine Learning Scientist - Bay Area, CA                                                             1
Sr Data Analyst                                                                                       1
RFP Data Analyst                                                                                      1
Computational Scientist                                                                               1
Geospatial Data Scientist                                                                             1
Say Business Data Analyst                                                                             1
ELISA RESEARCH SCIENTIST (CV-15)                                                                      1
Sr Scientist - Extractables & Leachables                                                              1
Staff Scientist- Upstream PD                                                                          1
Analytics Manager                                                                                     1
Scientist - Biomarker and Flow Cytometry                                                              1
Research Scientist Patient Preferences (Remote)                                                       1
AI Data Scientist                                                                                     1
Tableau Data Engineer 20-0117                                                                         1
Data Integration and Modeling Engineer                                                                1
Data Scientist (TS/SCI)                                                                               1
Software Engineer - Data Science                                                                      1
Production Engineer - Statistics/Data Analysis                                                        1
Statistical Scientist                                                                                 1
Health Data Scientist - Biomedical/Biostats                                                           1
Software Data Engineer                                                                                1
Data Scientist Machine Learning                                                                       1
Diversity and Inclusion Data Analyst                                                                  1
Manager / Lead, Data Science & Analytics                                                              1
NGS Scientist                                                                                         1
Director of Data Science                                                                              1
Data Scientist - Statistics, Mid-Career                                                               1
Staff BI and Data Engineer                                                                            1
Environmental Data Science                                                                            1
Computer Scientist 1                                                                                  1
Real World Evidence (RWE) Scientist                                                                   1
Operations Data Analyst                                                                               1
Applied Technology Researcher / Data Scientist                                                        1
Equity Data Insights Analyst - Quantitative Analyst                                                   1
Staff Data Scientist - Pricing                                                                        1
Report Writer-Data Analyst                                                                            1
Computational Scientist, Machine Learning                                                             1
Data Engineer (Remote)                                                                                1
Business Data Analyst                                                                                 1
Purification Scientist                                                                                1
Data Engineer, Enterprise Analytics                                                                   1
Data Science Instructor                                                                               1
Data Science Manager, Payment Acceptance - USA                                                        1
AI/ML - Machine Learning Scientist, Siri Understanding                                                1
Name: count, dtype: int64

In [312]:
df.J_Title.isna().sum()

5

In [316]:
df[df.J_Title.isna()]

,J_Title,J_Salary,J_Description,C_Rating,C_Name,C_Location,C_Headquarters,C_Size,C_Founded,C_Ownership Type,C_Industry,C_Sector,C_Revenue,C_Competitors
4,NaN,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
9,NaN,$137K-$171K (Glassdoor est.),Ready to write the best chapter of your career...,3.6,XSELL Technologies,"Chicago, IL","Chicago, IL",51 to 200 employees,2014,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
38,NaN,$75K-$131K (Glassdoor est.),Job Title: Data Scientists\n\nJob Description\...,2.2,Great-Circle Technologies,"Chantilly, VA","Chantilly, VA",1 to 50 employees,2000,Company - Private,Enterprise Software & Network Solutions,Information Technology,$1 to $5 million (USD),-1
290,NaN,$141K-$225K (Glassdoor est.),Work Authorization Those authorized to work in...,1.0,PETADATA,"San Francisco, CA","Fremont, CA",51 to 200 employees,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1
396,NaN,$110K-$163K (Glassdoor est.),"Meridian Knowledge Solutions, LLC, is the lead...",4.3,Visionary Integration Professionals,"Washington, DC","Folsom, CA",501 to 1000 employees,1996,Company - Private,IT Services,Information Technology,$100 to $500 million (USD),"CGI (Nevada), Accenture, Deloitte"

In [323]:
title_mode = df.J_Title.mode()
title_mode

0    Data Scientist
Name: J_Title, dtype: object

In [326]:
df.J_Title = df.J_Title.fillna("title_mode")

In [328]:
df.J_Title.isnull().sum()

0

In [329]:
df.head(5)

,J_Title,J_Salary,J_Description,C_Rating,C_Name,C_Location,C_Headquarters,C_Size,C_Founded,C_Ownership Type,C_Industry,C_Sector,C_Revenue,C_Competitors
0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,title_mode,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

##### Locating Erroneous Value

In [336]:
df.eq('-1').sum()

J_Title               0
J_Salary              0
J_Description         0
C_Rating              0
C_Name                0
C_Location            0
C_Headquarters       31
C_Size               27
C_Founded             0
C_Ownership Type     27
C_Industry           71
C_Sector             71
C_Revenue            27
C_Competitors       512
dtype: int64

In [337]:
(df.eq(-1) + df.eq("-1")).sum()

J_Title               0
J_Salary              0
J_Description         0
C_Rating              0
C_Name                0
C_Location            0
C_Headquarters       31
C_Size               27
C_Founded           119
C_Ownership Type     27
C_Industry           71
C_Sector             71
C_Revenue            27
C_Competitors       512
dtype: int64

In [349]:
cols = df.columns
cols

Index(['J_Title', 'J_Salary', 'J_Description', 'C_Rating', 'C_Name',
       'C_Location', 'C_Headquarters', 'C_Size', 'C_Founded',
       'C_Ownership Type', 'C_Industry', 'C_Sector', 'C_Revenue',
       'C_Competitors'],
      dtype='object')

In [355]:
for i in cols:
    df.loc[df[i].isin([-1,'-1'])] = np.NaN

In [356]:
df.isna().sum()

J_Title               0
J_Salary              0
J_Description         0
C_Rating              0
C_Name                0
C_Location            0
C_Headquarters       31
C_Size               27
C_Founded           119
C_Ownership Type     27
C_Industry           71
C_Sector             71
C_Revenue            27
C_Competitors       512
dtype: int64